"""RubiMorph conversion engine."""

from .convert import convert_text, convert_text_flexible
from .custom_profiles import (
    CustomFormatProfile,
    CustomParserRule,
    CustomTransformRule,
    PROFILE_EXTENSION,
    ProfileCapabilities,
    ProfileError,
    ProfileIssue,
    ProfileTimeoutError,
    ProfileValidationResult,
    RegisteredProfile,
    delete_registered_profile,
    export_registered_profile,
    import_profile_file,
    list_enabled_registered_profiles,
    load_registered_profiles,
    load_profile,
    parse_custom_tokens,
    profile_from_data,
    register_profile,
    render_custom_tokens,
    registered_profile_path,
    save_profile,
    set_registered_profile_enabled,
    user_profiles_dir,
    validate_profile_collection,
    validate_profile_data,
    validate_profile_file,
)
from .diagnostics import diagnose
from .fileops import FileConversionResult, convert_directory, convert_file
from .parser import parse_to_tokens
from .platform_profiles import (
    PLATFORM_LABELS,
    PLATFORM_PROFILES,
    PLATFORM_STATUS_VALUES,
    SUPPORTED_PLATFORM_IDS,
    PlatformProfile,
    get_platform_profile,
    list_platform_profiles,
)
from .renderer import render_from_tokens, target_uses_plain_ruby_mode
from .types import (
    AnnotationToken,
    BreakToken,
    ConversionResult,
    Diagnostic,
    EmphasisToken,
    HeadingToken,
    HorizontalRuleToken,
    MarkdownToken,
    PageBreakToken,
    PlatformSpecificToken,
    RawHtmlToken,
    RawToken,
    RenderOptions,
    RubyToken,
    StrongToken,
    TextToken,
    Token,
    UnknownMarkupToken,
    UnsupportedToken,
)
from .version import APP_NAME, __version__, get_version

__all__ = [
    "APP_NAME",
    "PLATFORM_LABELS",
    "PLATFORM_PROFILES",
    "PLATFORM_STATUS_VALUES",
    "SUPPORTED_PLATFORM_IDS",
    "AnnotationToken",
    "BreakToken",
    "ConversionResult",
    "CustomFormatProfile",
    "CustomParserRule",
    "CustomTransformRule",
    "PROFILE_EXTENSION",
    "Diagnostic",
    "EmphasisToken",
    "FileConversionResult",
    "HeadingToken",
    "HorizontalRuleToken",
    "MarkdownToken",
    "PageBreakToken",
    "PlatformProfile",
    "PlatformSpecificToken",
    "ProfileCapabilities",
    "ProfileError",
    "ProfileIssue",
    "ProfileTimeoutError",
    "ProfileValidationResult",
    "RegisteredProfile",
    "RawHtmlToken",
    "RawToken",
    "RenderOptions",
    "RubyToken",
    "StrongToken",
    "TextToken",
    "Token",
    "UnknownMarkupToken",
    "UnsupportedToken",
    "__version__",
    "convert_directory",
    "convert_file",
    "convert_text",
    "convert_text_flexible",
    "delete_registered_profile",
    "diagnose",
    "export_registered_profile",
    "get_platform_profile",
    "get_version",
    "import_profile_file",
    "list_enabled_registered_profiles",
    "list_platform_profiles",
    "load_registered_profiles",
    "load_profile",
    "parse_to_tokens",
    "parse_custom_tokens",
    "profile_from_data",
    "registered_profile_path",
    "register_profile",
    "render_custom_tokens",
    "render_from_tokens",
    "target_uses_plain_ruby_mode",
    "save_profile",
    "set_registered_profile_enabled",
    "user_profiles_dir",
    "validate_profile_collection",
    "validate_profile_data",
    "validate_profile_file",
]
