"""Platform profile definitions for RubiMorph."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

PlatformStatus = Literal["supported", "partial", "planned", "research-needed", "unsupported"]
VerificationStatus = Literal[
    "official-confirmed",
    "official-partial",
    "official-not-found",
    "needs-login-or-js",
    "research-needed",
]

PLATFORM_STATUS_VALUES: tuple[str, ...] = (
    "supported",
    "partial",
    "planned",
    "research-needed",
    "unsupported",
)


@dataclass(frozen=True)
class PlatformProfile:
    platform_id: str
    label: str
    official_url: str
    verification_status: VerificationStatus
    status: PlatformStatus
    input_markup: tuple[str, ...]
    output_markup: tuple[str, ...]
    ruby_syntax: str
    emphasis_syntax: str
    annotation_syntax: str
    html_allowed: bool
    markdown_allowed: bool
    escape_rules: str
    loss_risks: tuple[str, ...]
    warning_conditions: tuple[str, ...]


PLATFORM_PROFILES: dict[str, PlatformProfile] = {
    "kakuyomu": PlatformProfile(
        platform_id="kakuyomu",
        label="カクヨム",
        official_url="https://kakuyomu.jp/help/entry/notation",
        verification_status="official-confirmed",
        status="supported",
        input_markup=("ruby", "emphasis"),
        output_markup=("ruby", "emphasis"),
        ruby_syntax="｜親文字《ルビ》 / |親文字《ルビ》 / 漢字《ルビ》",
        emphasis_syntax="《《傍点対象》》",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="《をそのまま表示する場合は直前に縦線を置く。",
        loss_risks=("ルビと傍点の同時指定は再現できない。",),
        warning_conditions=("改行またぎのルビ・傍点", "長すぎる親文字またはルビ"),
    ),
    "narou": PlatformProfile(
        platform_id="narou",
        label="小説家になろう",
        official_url="https://syosetu.com/helpcenter/helppage/helppageid/42",
        verification_status="official-confirmed",
        status="supported",
        input_markup=("ruby",),
        output_markup=("ruby",),
        ruby_syntax="｜親文字《ルビ》 / |親文字《ルビ》 / 漢字《ルビ》 / 漢字(ルビ)",
        emphasis_syntax="入力補助機能はあるが、本文内記法の公式仕様は要確認。",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="() をルビ化したくない場合は直前に縦線を置く。",
        loss_risks=("傍点は現在の実装では情報欠落または要確認扱い。",),
        warning_conditions=("丸括弧ルビ", "長いルビ", "傍点変換"),
    ),
    "estar": PlatformProfile(
        platform_id="estar",
        label="エブリスタ",
        official_url="https://support.estar.jp/hc/ja/articles/360020301874",
        verification_status="official-confirmed",
        status="supported",
        input_markup=("ruby", "emphasis"),
        output_markup=("ruby", "emphasis"),
        ruby_syntax="｜親文字《ルビ》 / |親文字《ルビ》 / 漢字《ルビ》",
        emphasis_syntax="《《傍点対象》》",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="《》をそのまま表示する場合は直前に縦線を置く。",
        loss_risks=("ルビと傍点の同時指定は再現できない。",),
        warning_conditions=("改行またぎのルビ・傍点", "長すぎる親文字またはルビ"),
    ),
    "novelup": PlatformProfile(
        platform_id="novelup",
        label="ノベルアップ＋",
        official_url="https://novelup.plus/help/detail/%E5%85%A5%E5%8A%9B%E8%A3%9C%E5%8A%A9%E6%A9%9F%E8%83%BD%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6",
        verification_status="official-partial",
        status="partial",
        input_markup=("ruby", "emphasis"),
        output_markup=("ruby", "emphasis"),
        ruby_syntax="入力補助機能あり。本文内記法の詳細は要確認。",
        emphasis_syntax="入力補助機能あり。本文内記法の詳細は要確認。",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式ページから本文内記法の詳細を確認しきれていない。",),
        warning_conditions=("公式仕様未確認の記法"),
    ),
    "pixiv": PlatformProfile(
        platform_id="pixiv",
        label="pixiv小説",
        official_url="https://www.pixiv.help/hc/ja/articles/39197091470105",
        verification_status="official-confirmed",
        status="supported",
        input_markup=("ruby", "emphasis", "strong"),
        output_markup=("ruby", "emphasis", "strong"),
        ruby_syntax="[[rb: 親文字 > ルビ]]",
        emphasis_syntax="[[emphasismark: 対象 > •]]",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="pixiv特殊タグ内の > と ]] は要注意。",
        loss_risks=("pixiv独自タグを他形式へ変換するとタグ種別が失われる場合がある。",),
        warning_conditions=("pixiv特殊タグ構文不正", "独自タグの未対応"),
    ),
    "aozora": PlatformProfile(
        platform_id="aozora",
        label="青空文庫",
        official_url="https://www.aozora.gr.jp/aozora-manual/index-input.html",
        verification_status="official-confirmed",
        status="supported",
        input_markup=("ruby", "annotation", "emphasis"),
        output_markup=("ruby", "annotation", "emphasis"),
        ruby_syntax="｜親文字《ルビ》 / 漢字《ルビ》",
        emphasis_syntax="［＃「対象」に傍点］",
        annotation_syntax="［＃...］",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="注記記号とルビ区切りは全角を使う。",
        loss_risks=("青空文庫注記は多様なため現在の実装では一部のみ対応。",),
        warning_conditions=("未知の入力者注", "入れ子注記", "改行またぎ"),
    ),
    "note": PlatformProfile(
        platform_id="note",
        label="note",
        official_url="https://www.help-note.com/hc/ja/articles/4406430353817",
        verification_status="official-confirmed",
        status="partial",
        input_markup=("ruby", "markdown-like"),
        output_markup=("ruby",),
        ruby_syntax="｜親文字《ルビ》 / |親文字《ルビ》",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="太字やリンクとの組み合わせはルビ記法全体への指定が必要。",
        loss_risks=("太字・リンクとルビの組み合わせは現在の実装では保持しない。",),
        warning_conditions=("複合装飾", "公式仕様未確認の装飾"),
    ),
    "alphapolis": PlatformProfile(
        platform_id="alphapolis",
        label="アルファポリス",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "hameln": PlatformProfile(
        platform_id="hameln",
        label="ハーメルン",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "novelpia": PlatformProfile(
        platform_id="novelpia",
        label="ノベルピア",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "maho_i_land": PlatformProfile(
        platform_id="maho_i_land",
        label="魔法のiらんど",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "berry_cafe": PlatformProfile(
        platform_id="berry_cafe",
        label="ベリーズカフェ",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "noichigo": PlatformProfile(
        platform_id="noichigo",
        label="野いちご",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "tapnovel": PlatformProfile(
        platform_id="tapnovel",
        label="TapNovel",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "pri_shosetsu": PlatformProfile(
        platform_id="pri_shosetsu",
        label="プリ小説",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "uranai_tkool": PlatformProfile(
        platform_id="uranai_tkool",
        label="占いツクール",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "arcadia": PlatformProfile(
        platform_id="arcadia",
        label="Arcadia",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "fc2_novel": PlatformProfile(
        platform_id="fc2_novel",
        label="FC2小説",
        official_url="",
        verification_status="research-needed",
        status="research-needed",
        input_markup=(),
        output_markup=(),
        ruby_syntax="要確認",
        emphasis_syntax="要確認",
        annotation_syntax="要確認",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="要確認",
        loss_risks=("公式仕様未確認。",),
        warning_conditions=("未調査プラットフォーム"),
    ),
    "wordpress": PlatformProfile(
        platform_id="wordpress",
        label="WordPress",
        official_url="https://wordpress.org/documentation/",
        verification_status="research-needed",
        status="planned",
        input_markup=("html", "markdown"),
        output_markup=("html", "markdown"),
        ruby_syntax="HTML ruby またはプラグイン依存。要確認。",
        emphasis_syntax="HTML / Markdown",
        annotation_syntax="要確認",
        html_allowed=True,
        markdown_allowed=True,
        escape_rules="HTMLエスケープとブロックエディタ仕様を要確認。",
        loss_risks=("ブロック変換時にHTML構造が変わる可能性。",),
        warning_conditions=("ブロックエディタ依存", "HTMLタグ"),
    ),
    "hatena_blog": PlatformProfile(
        platform_id="hatena_blog",
        label="はてなブログ",
        official_url="",
        verification_status="research-needed",
        status="planned",
        input_markup=("html", "markdown"),
        output_markup=("html", "markdown"),
        ruby_syntax="HTML ruby または編集モード依存。要確認。",
        emphasis_syntax="HTML / Markdown",
        annotation_syntax="要確認",
        html_allowed=True,
        markdown_allowed=True,
        escape_rules="編集モード依存。要確認。",
        loss_risks=("編集モードにより出力が変わる。",),
        warning_conditions=("編集モード未指定"),
    ),
    "epub_xhtml": PlatformProfile(
        platform_id="epub_xhtml",
        label="EPUB / XHTML",
        official_url="https://www.w3.org/TR/epub-33/",
        verification_status="research-needed",
        status="planned",
        input_markup=("html",),
        output_markup=("html",),
        ruby_syntax="<ruby><rt>",
        emphasis_syntax="CSS text-emphasis または span。要確認。",
        annotation_syntax="要確認",
        html_allowed=True,
        markdown_allowed=False,
        escape_rules="XHTMLとして整形式にする必要がある。",
        loss_risks=("CSS依存の表現はビューア差がある。",),
        warning_conditions=("XHTML整形式", "CSS依存"),
    ),
    "html": PlatformProfile(
        platform_id="html",
        label="HTML ruby",
        official_url="https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-ruby-element",
        verification_status="official-partial",
        status="supported",
        input_markup=("html", "ruby"),
        output_markup=("html", "ruby", "emphasis"),
        ruby_syntax="<ruby>親文字<rt>ルビ</rt></ruby>",
        emphasis_syntax="<span class=\"emphasis\">対象</span>",
        annotation_syntax="HTMLコメント等は現在の実装では保持対象外。",
        html_allowed=True,
        markdown_allowed=False,
        escape_rules="テキストはHTMLエスケープする。",
        loss_risks=("HTML ruby 以外のタグは変換先で残るか失われる可能性。",),
        warning_conditions=("未知HTMLタグ", "RawHtmlToken"),
    ),
    "markdown": PlatformProfile(
        platform_id="markdown",
        label="Markdown",
        official_url="https://spec.commonmark.org/",
        verification_status="official-partial",
        status="partial",
        input_markup=("markdown", "plain"),
        output_markup=("markdown", "plain"),
        ruby_syntax="親文字（ルビ）に簡略化。",
        emphasis_syntax="**対象** に簡略化。",
        annotation_syntax="要確認",
        html_allowed=True,
        markdown_allowed=True,
        escape_rules="CommonMark準拠の厳密なエスケープは現在の実装では未実装。",
        loss_risks=("ルビや傍点は標準Markdownに同等表現がない。",),
        warning_conditions=("標準Markdownへの簡略化"),
    ),
    "plain": PlatformProfile(
        platform_id="plain",
        label="プレーンテキスト",
        official_url="",
        verification_status="official-not-found",
        status="supported",
        input_markup=("plain",),
        output_markup=("plain",),
        ruby_syntax="削除または 親文字（ルビ）",
        emphasis_syntax="装飾を外して本文のみ。",
        annotation_syntax="装飾を外して本文のみ。",
        html_allowed=False,
        markdown_allowed=False,
        escape_rules="なし",
        loss_risks=("すべての装飾情報が失われる。",),
        warning_conditions=("装飾の簡略化"),
    ),
}

SUPPORTED_PLATFORM_IDS: tuple[str, ...] = (
    "kakuyomu",
    "narou",
    "estar",
    "pixiv",
    "aozora",
    "html",
    "markdown",
    "plain",
)

PLATFORM_LABELS: dict[str, str] = {
    platform_id: profile.label for platform_id, profile in PLATFORM_PROFILES.items()
}


def get_platform_profile(platform_id: str) -> PlatformProfile:
    try:
        return PLATFORM_PROFILES[platform_id]
    except KeyError as exc:
        supported = ", ".join(PLATFORM_PROFILES)
        raise ValueError(f"unsupported platform: {platform_id!r}. supported: {supported}") from exc


def list_platform_profiles() -> tuple[PlatformProfile, ...]:
    return tuple(PLATFORM_PROFILES.values())


def is_parse_supported(platform_id: str) -> bool:
    profile = get_platform_profile(platform_id)
    return profile.status in {"supported", "partial"}


def is_render_supported(platform_id: str) -> bool:
    profile = get_platform_profile(platform_id)
    return profile.status in {"supported", "partial"}
